version: '3.9'

services:
  php-fpm:
    container_name: nutrition-app
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ./src:/var/www/html

  web:
    image: nginx:latest
    ports:
      - '8731:80'
    volumes:
      - ./src:/var/www/html
      - ./nginx_default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
