version: '3.9'

services:
  php-fpm:
    container_name: nutrition-app
    build: .
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    networks:
      - app-network

  web:
    image: nginx:alpine
    container_name: nutrition-web
    ports:
      - '8731:80'
    volumes:
      - ./src:/var/www/html
      - ./nginx_default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    networks:
      - app-network
    links:
      - php-fpm

networks:
  app-network:
     driver: bridge
