# Github action for testing
name: build
on: [push, pull_request]
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php-versions: ['8.1', '8.2']
        steps:
        - name: Checkout
          uses: actions/checkout@v3

        # Docs: https://github.com/shivammathur/setup-php
        - name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: ${{ matrix.php-versions }}
            tools: cs2pr, phpcs, phpunit

        - name: Install dependencies
          run: composer install --prefer-dist --no-progress --no-suggest
          working-directory: ${{ github.workspace }}/src

        - name: Check code style
          run: phpcs --standard=PSR12--report=checkstyle src/App src/Tests src/Public | cs2pr

        - name: Run tests
          run: phpunit
          working-directory: ${{ github.workspace }}/src
